- name: "Install ansible docker requirements"
  apt:
    name: python-setuptools
    state: installed
    update_cache: True

- name: "Install python pip"
  easy_install:
    name: pip
    state: latest

- name: "Install docker-py and pexpect"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pexpect
    - docker-py

- name: "Checking if docker is installed"
  command: which docker
  register: docker
  ignore_errors: True

- name: "Docker install"
  include: docker_install.yml
  become: True
  when: docker|failed
